#!/bin/bash

# files
WORKDIR=/usr/local/nagios/libexec

# oid
HEALTH_OID_LIST=(
.1.3.6.1.4.1.2.3.51.3.1.1.2.1.11
.1.3.6.1.4.1.2.3.51.3.1.2.2.1.11
.1.3.6.1.4.1.2.3.51.3.1.3.2.1.10
.1.3.6.1.4.1.2.3.51.3.1.5.20.1.11
.1.3.6.1.4.1.2.3.51.3.1.5.21.1.8
.1.3.6.1.4.1.2.3.51.3.1.11.2.1.6
.1.3.6.1.4.1.2.3.51.3.1.12.2.1.3
.1.3.6.1.4.1.2.3.51.3.1.13.1.3.1.11
)
HEALTH_OID=.1.3.6.1.4.1.2.3.51.3.1.4.1.0
OK_STATUS='normal\(255\)'

function usage(){
  cat << EOL
  Usage
    check_ibm_hardware IPaddress
EOL
exit 0
}

# arguments check
[ $# -eq 0 ] && usage
HOST=$1

# snmp parameter
COM=public
     WALK="/usr/bin/snmpwalk -v1 -c $COM -O n $HOST"
WALK_NAME="/usr/bin/snmpwalk -v1 -c $COM $HOST"

# Nagios status
RET_OK=0
RET_WARN=1
RET_CRIT=2
RET_UNKNOWN=3

# Check parameter
RESULT=0

#
# Main
#

# ヘルスチェック
RESULT=`$WALK $HEALTH_OID |awk "\\$4 ~ /$OK_STATUS/ {print \\$4}" |wc -l`

# 結果と正否を返却
if [ $RESULT -eq 1 ]; then
  echo "IBM Hardware OK"
  exit $RET_OK

else
  echo "IBM Hardware NG"

  for oid_parent in ${HEALTH_OID_LIST[@]}
  do
    $WALK_NAME $oid_parent |grep -v Normal
  done

  exit $RET_CRIT
fi
